### ISSUE TITLE
runtime error if celery task method has no return value

### ISSUE THREAD

**Issue by shicky** [shicky/gocelery#14]
runtime error if celery task method has no return value.

``` bash
panic: runtime error: index out of range

goroutine 10 [running]:
panic(0x86dbc0, 0xc82000a120)
    /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/shicky/gocelery.(*CeleryWorker).RunTask(0xc8200165f0, 0xc820168060, 0xc82015bf50, 0x0, 0x0)
    /home/secret/gowork/src/github.com/shicky/gocelery/worker.go:130 +0x87f
github.com/shicky/gocelery.(*CeleryWorker).StartWorker.func1(0xc8200165f0, 0xc820011b90, 0x24)
    /home/secret/gowork/src/github.com/shicky/gocelery/worker.go:55 +0x290
created by github.com/shicky/gocelery.(*CeleryWorker).StartWorker
    /home/secret/gowork/src/github.com/shicky/gocelery/worker.go:69 +0x104
```

**Comment by shicky** [comment]
Fixed 13e2e2ee17c05778f4cbb55e58ad8fc19a573aaa
Needs to add corresponding test.
